source = document.getElementById("random")

randomId = [
    # credit to nationstates
    "The Democratic People's Republic Of",
    "The Kingdom of",
    "The Republic of",
    "The Empire of",
    "The Commonwealth of",
    "The Federation of",
    "The Colony of",
    "The Principality of",
    "The Protectorate of",
    "The United States of",
    "The United Kingdom of",
    "The Democratic Republic of",
    "The Confederacy of",
    "The Dominion of",
    "The Sultanate of",
    "The Holy Empire of",
    "The Theocracy of",
    "The Most Serene Republic of",
    "The United Socialist States of",
    "The Democratic States of",
    "The Allied States of",
    "The Queendom of",
    "The Fiefdom of",
    "The Constitutional Monarchy of",
    "The Dictatorship of",
    "The Matriarchy of",
    "The Emirate of",
    "The Grand Duchy of",
    "The Free Land of",
    "The Community of",
    "The Disputed Territories of",
    "The Jingoistic States of",
    "The Armed Republic of",
    "The Nomadic Peoples of",
    "The Oppressed Peoples of",
    "The Borderlands of",
    "The Rogue Nation of",
    "The Incorporated States of",
    "The Federal Republic of"
]

randomArea = [
    "North",
    "South",
    "East",
    "West",
    "Central",
    ""
]

randomCountry = [
    # credit to history.state.gov
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Austrian Empire",
    "Azerbaijan",
    "Baden",
    "The Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Bavaria",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Brunswick and Lüneburg",
    "Bulgaria",
    "Burkina Faso",
    "Burma",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "The Cayman Islands",
    "Central African Republic",
    "Central American Federation",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "The Congo Free State",
    "Costa Rica",
    "Cote d’Ivoire (Ivory Coast)",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Czechoslovakia",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "The Duchy of Parma",
    "East Germany (German Democratic Republic)",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Federal Government of Germany",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "The Gambia",
    "Georgia",
    "Ghana",
    "The Grand Duchy of Tuscany",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Hanover",
    "Hanseatic Republics",
    "Hawaii",
    "Hesse",
    "Holy See",
    "Honduras",
    "Hungary",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kingdom of Serbia/Yugoslavia",
    "Kiribati",
    "Korea",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Lew Chew (Loochoo)",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mecklenburg-Schwerin",
    "Mecklenburg-Strelitz",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nassau",
    "Nauru",
    "Nepal",
    "The Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North German Confederation",
    "North German Union",
    "North Macedonia",
    "Norway",
    "Oldenburg",
    "Oman",
    "Orange Free State",
    "Pakistan",
    "Palau",
    "Panama",
    "Papal States",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Piedmont-Sardinia",
    "Poland",
    "Portugal",
    "Qatar",
    "Republic of Genoa",
    "Republic of the Congo",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Schaumburg-Lippe",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "The Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Texas",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Two Sicilies",
    "Uganda",
    "Ukraine",
    "Union of Soviet Socialist Republics",
    "The United Arab Emirates",
    "The United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Württemberg",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]





rsp = "#{randomId[Math.floor(Math.random() * randomId.length)]}
 #{randomArea[Math.floor(Math.random() * randomArea.length)]}
 #{randomCountry[Math.floor(Math.random() * randomCountry.length)]}"


source.innerHTML = "#{rsp}"
